redis:
  image: redis

django:
  build: .
  command: ./compose/run_django.sh
  ports:
    - "8000:8000"
  volumes:
    - .:/django-rq
  links:
    - redis

rq:
  build: .
  command: ./compose/run_rq.sh
  volumes:
    - .:/django-rq
  links:
    - redis

rqscheduler:
  build: .
  command: ./compose/run_rqscheduler.sh
  volumes:
    - .:/django-rq
  links:
    - redis

# For dashboard w/o Flask:
# pip install rq-dashboard==0.3.4
# https://github.com/nvie/rq-dashboard/issues/99
rqdashboard:
  build: .
  command: ./compose/run_rqdashboard.sh
  ports:
    - "9181:9181"
  volumes:
    - .:/django-rq
  links:
    - redis
